### ISSUE TITLE
Server down for dialogue_act_annotator.py

### ISSUE THREAD

**Issue by ShivaliGoel** [bothe/EDAs#2]
Hi I get the following error message when trying out dialogue_act_annotator.py. 
The given LINK might be broken if the server is down - so try again or contact author
Will it get fixed?

**Comment by bothe** [comment]
Hi, the link is updated, and you can now try.
Sorry for the long delay to answer, there was some technical issue. 
I am also planning to launch the server backend soon, the heavy resource is, of course, the word embedding part.
You can also try my web-application for the same server backend: https://crbothe.github.io/discourse-wizard/
I will close the issue with this comment.
Thanks for trying out my experiments.

**Comment by bothe** [comment]
Would be nice to keep it open and you can tell me if it is working now! @ShivaliGoel
